In [3]:
import numpy as np
import pandas as pd

Data = pd.read_csv('CS598PS_Project_master/friends/labels',sep='\t',header=None)
data = Data.iloc[0:135]
#labels1 = np.array(labels.iloc[1::2,0])
#labels1 = np.hstack([labels.iloc[0,0],labels1])
#print(labels1.shape)
#labels2 = pd.get_dummies(labels.iloc[::2,1])
#labels2 = np.array(labels2)
#print(labels1.shape)
#labels = np.zeros((135,9))
#labels[:,0] = labels1
#labels[:,1:9] = labels2
labels = pd.DataFrame(np.zeros((607,1)))
for i in range(135):
    first = int(data.iloc[i,2])
    second = int(data.iloc[i,3])
    labels.iloc[first:second,0]=data.iloc[i,1]
for i in range(607):
    if labels.iloc[i,0] == 'R':
        labels.iloc[i,0] = 1
    if labels.iloc[i,0] == 'C':
        labels.iloc[i,0] = 2
    if labels.iloc[i,0] == 'M':
        labels.iloc[i,0] = 3
    if labels.iloc[i,0] == 'J':
        labels.iloc[i,0] = 4
    if labels.iloc[i,0] == 'S':
        labels.iloc[i,0] = 5
    if labels.iloc[i,0] == 'P':
        labels.iloc[i,0] = 6
    if labels.iloc[i,0] == 'X':
        labels.iloc[i,0] = 7
    if labels.iloc[i,0] == 'Z':
        labels.iloc[i,0] = 8
Labels = pd.get_dummies(labels)
Labels.shape

(607, 9)

In [4]:
from scipy.io.wavfile import read as wavread
from scipy.signal import stft
import numpy as np
import matplotlib.pyplot as plt
from librosa.feature import mfcc
import librosa.display
from scipy import signal

# Load the file and convert to floating point
import scipy.io.wavfile
fs,s = scipy.io.wavfile.read('FriendsS09E01.wav')
s = s.astype( float)
print(s.shape,fs)
plt.subplot( 2, 1, 1), plt.plot( np.arange( 0, len( s))/fs, s)
plt.title( 'Input sound'), plt.xlabel( 'Time (sec)')
plt.show()
# Get the magnitude spectrogram
f, t, S = signal.stft(s,window=signal.get_window('hann',1024),noverlap=768,nperseg = 1024)
partition = len(s)/fs
slide = int(S.shape[1]//partition+1)
k = 0
data_slide = []
print(partition,slide)
while k < partition:
    left = k*slide
    right = min(S.shape[1]+1,(k+1)*slide)
    par = S[:,left:right]
    data_slide.append(par)
    k += 1
print(len(data_slide),data_slide[0].shape)

(71989248,) 48000


<Figure size 640x480 with 1 Axes>

1499.776 188
1500 (513, 188)


In [5]:
train = np.asarray(data_slide[0:607])
test = np.asarray(data_slide[607:-6])
f.shape,t.shape,s.shape,fs,len(s)/fs,S.shape,train.shape,Labels.shape,labels.shape,test.shape

((513,),
 (281209,),
 (71989248,),
 48000,
 1499.776,
 (513, 281209),
 (607, 513, 188),
 (607, 9),
 (607, 1),
 (887, 513, 188))

In [6]:
# Take as SVM with stacking
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

train_linear = np.zeros((607*188,513))
label_linear = np.zeros((607*188,1))
Label_linear = np.zeros((607*188,1))
for i in range(train.shape[0]):
    for j in range(train.shape[2]):
        train_linear[i*j,:] = train[i,:,j]
        label_linear[i*j,0] = labels.iloc[i,0]
        Label_linear[i*j,0] = Label_linear[i,0]
print(train_linear.shape,label_linear.shape)
#clf = SVC(gamma='auto')
#clf.fit(train_linear, label_linear.ravel())
#clf.get_params()
print('completed')

/Users/xiujiayang/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: ComplexWarning: Casting complex values to real discards the imaginary part
  # Remove the CWD from sys.path while we load stuff.


(114116, 513) (114116, 1)
completed


In [19]:
# Use sample to generate classifier
def get_train(file):
    fs,s = scipy.io.wavfile.read(file)
    s = s.astype(float)
    print(s.shape)
    f, t, S = signal.stft(s,window=signal.get_window('hann',1024),noverlap=768,nperseg = 1024)
    partition = len(s)/fs
    slide = int(S.shape[1]//partition+1)
    k = 0
    data_slide = []
    while k < partition:
        left = k*slide
        right = min(S.shape[1]+1,(k+1)*slide)
        par = S[:,left:right]
        data_slide.append(par)
        k += 1
    i = 1
    while data_slide[-i].shape[1] != 188:
        i += 1
    return data_slide[:-(i+1)]
train_j = get_train('J-Final-48k.wav')
train_m = get_train('M-Final-48k.wav')
train_r = get_train('R-Final-48k.wav')
train_s = get_train('S-Final-48k.wav')
labels_j = np.ones((len(train_j),1))*4
labels_m = np.ones((len(train_m),1))*3
labels_r = np.ones((len(train_r),1))
labels_s = np.ones((len(train_s),1))*5
train_data = train_j+train_m+train_r+train_s
train_data = np.asarray(train_data)
train_label = np.vstack([labels_j,labels_m,labels_r,labels_s])
print(train_data.shape,train_label.shape)

(7323410,)
(7136310,)
(6377744,)
(5531383,)
(538, 513, 188) (538, 1)


In [20]:
training = np.zeros((train_data.shape[0]*train_data.shape[2],train_data.shape[1]))
labeling = np.zeros((train_data.shape[0]*train_data.shape[2],1))
for i in range(train_data.shape[0]):
    for j in range(train_data.shape[2]):
        training[i*j,:] = train_data[i,:,j]
        labeling[i*j,0] = labels.iloc[i,0]
print(training.shape,labeling.shape)

/Users/xiujiayang/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: ComplexWarning: Casting complex values to real discards the imaginary part
  """


(101144, 513) (101144, 1)


In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

clf = LogisticRegression(solver='lbfgs',multi_class='multinomial').fit(training,labeling)
print('train ready')
predict = clf.predict(train_linear)
confusion_train = confusion_matrix(label_linear,predict)
print(confusion_train)

/Users/xiujiayang/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


train ready
[[84857   121   223    68   269   234   340   115    42]
 [ 5333    46   125    40   111    71    75    28    27]
 [ 3713    40    80    30    81    80    57    35    16]
 [  640     2     9     4    17     4     9     6     3]
 [ 5322    49   144    49   128   135   108    51    20]
 [ 3073    24    25    17    36    28    26     9     7]
 [ 4244    32    61    34    96    48    72    22    18]
 [ 1003     6    12     4    14    10     7     6     0]
 [ 2051    13    46    10    48    30    20     3     4]]


/Users/xiujiayang/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
